$ANSIBLE_VAULT;1.1;AES256
37393839393930613566613932613862626661626361383034346466653438626535386265666563
3063643939626164333436633735613066343135646639300a396564356336363230386462363134
65303764646565613862613131646265656537633265633438303838326633633636373232623238
3438613362363931300a323335633261363730646234656133316632656461313834613130666530
65396435356334323430613330313236313430626333303432646133663864363537666532646138
39353730336335333564643466313931343661366463666135346534313439323864633432363938
35393861656336353761316236373732623565613036393761636665623437366361393432333931
33363032363363393365623634363866336332333931313130373937376231323066366234356637
37393066623462303632343332316165636436306537626530313930623733373634343762393737
34616661363564396336333934663861313161356531663334373461616639663035613766636339
37313065643036386133643837366232353539623962663932386231356539393636353466376666
34313565353262313938366662646336386630346564366233336539653132313263376439393131
61366630663064363364373839353265366363353035313061613362323963616662613331376636
36373664663263353563623630363831663563653335643339313733363262326461353530303338
35623731616662616438356263613163653966333138353064383933333638336564626665393466
37326466396262653539626665653062356561373333623635326339343166306231653466373636
32363565333739323835363330633766386139643637633261623562616431633637633165346537
63363866313638383562646437366464653634353362316632393163663362646234343965623966
34386163336637306133646632386564373737663439633163346666316461623137353933333166
34376466323561643933326166653233366363323934363837323933623035313764613737666138
64346335636434356463393863323634636533646637333432646532373262393530306164373035
36313931356232373464663231386135306332306563633965346332313532663332623937333038
376335666336343035626532346531306437
