all:
  hosts:
    piserver:
      ansible_host: piserver.local
      ansible_user: kevin
      ansible_become: true
      ansible_become_method: sudo
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
